import os
from dotenv import load_dotenv

load_dotenv()

AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_KEY = os.getenv("AZURE_OPENAI_KEY")

CHAT_DEPLOYMENT = os.getenv("CHAT_DEPLOYMENT")
TRANSCRIBE_DEPLOYMENT = os.getenv("TRANSCRIBE_DEPLOYMENT")

API_VERSION_CHAT = os.getenv("API_VERSION_CHAT")
API_VERSION_TRANSCRIBE = os.getenv("API_VERSION_TRANSCRIBE")

MS_TENANT_ID = os.getenv("MS_TENANT_ID")
MS_CLIENT_ID = os.getenv("MS_CLIENT_ID")
MS_CLIENT_SECRET = os.getenv("MS_CLIENT_SECRET")
SHAREPOINT_FILE_URL = os.getenv("SHAREPOINT_FILE_URL")
